a = %w( 
  gopro_ski
  gopro_ski​
  ​zelenkal
  zelenkal​
  ​executiveskibum
  executiveskibum​
  ​midwestshred
  midwestshred​
  ​instagraemedunn
  instagraemedunn​
  ​joemoomoo10
  joemoomoo10​
  ​sabrinaeberhard
  sabrinaeberhard​
  ​corbettssnow
  corbettssnow​
  ​skidmi
  skidmi​
  ​crystalisland
  crystalisland​
  ​sabrinaeberhard
  sabrinaeberhard​
  ​urquhak
  urquhak​
  ​corbettssnow
  corbettssnow​
  ​chloehewxx
  chloehewxx​
  ​lillie_photography_
  lillie_photography_​
  ​nyles_s
  nyles_s​
  ​foie_gras
  foie_gras​
  ​foie_gras
  foie_gras​
  ​minimum6_skiing
  minimum6_skiing​
  ​hsiaovincent
  hsiaovincent​
  ​rachshredgnar
  rachshredgnar​
  ​miguelrodden
  miguelrodden​
  ​lillie_photography_
  lillie_photography_​
  ​noemie.xo_love
  noemie.xo_love​
  ​mountain_mercantile
  mountain_mercantile​
  ​cmason770
  cmason770​
  ​lombardphoto
  lombardphoto​
  ​mountain_mercantile
  mountain_mercantile​
  ​mjdeeble
  mjdeeble​
  ​crystal_raye88
  crystal_raye88​
  ​rowemery
  rowemery​
  ​knockclothing
  knockclothing​
  ​k_caudill
  k_caudill​
  )

b = a.select { |e| a.index(e).even? }

puts b