development:
  adapter: postgresql
  database: snowcial_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: snowcial_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: snowcial
  pool: 5
  timeout: 5000